# Generated by Django 2.2 on 2020-06-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
