# Generated by Django 2.2 on 2020-06-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20200603_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
