# Generated by Django 2.2 on 2020-05-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninjas',
            new_name='Ninja',
        ),
    ]
